collab-ui/collab-ui-react

- src/lib/Accordion/__snapshots__/index.spec.js.snap
- src/lib/Accordion/index.js
- src/lib/Accordion/index.spec.js
- src/lib/AccordionGroup/__snapshots__/index.spec.js.snap
- src/lib/AccordionGroup/index.js
- src/lib/AccordionGroup/index.spec.js
- src/lib/AccordionHeader/__snapshots__/index.spec.js.snap
- src/lib/AccordionHeader/index.js
- src/lib/AccordionHeader/index.spec.js
Controlling the separator in accordion with a prop.
This PR is Dependent on https://github.com/collab-ui/collab-ui-core/pull/9
@pauljeter @bfbiggs @collab-ui/collab-jedi
> feat(Accordion): showing separator based on a prop

- src/docs/containers/NavBar/index.js
- src/lib/List/index.js
- src/lib/List/index.spec.js
- src/lib/ListItem/index.js
- src/lib/ListItemHeader/__snapshots__/index.spec.js.snap
- src/lib/ListItemHeader/index.js
- src/lib/ListItemHeader/index.spec.js
- src/lib/SpaceListItem/index.js
- src/lib/index.js
> feat(ListItemHeader): created and added styles

- src/lib/CollapseButton/__snapshots__/index.spec.js.snap
- src/lib/CollapseButton/index.js
- src/lib/CollapseButton/index.spec.js
- src/lib/index.js
@pauljeter @bfbiggs @collab-ui/collab-jedi
> feat(CollapseButton): Implementation for collapse button

- src/lib/Avatar/__snapshots__/index.spec.js.snap
- src/lib/Avatar/index.js
- src/lib/Avatar/index.spec.js
- src/lib/CompositeAvatar/__snapshots__/index.spec.js.snap
- src/lib/SpaceListItem/__snapshots__/index.spec.js.snap
@pauljeter @bfbiggs @collab-ui/collab-jedi
> feat(Avatar2): Adding bot,failurebadge,typing types to Avatar

- src/lib/Slider/__snapshots__/index.spec.js.snap
- src/lib/Slider/index.js
Fixing the alignment issue of SliderLabel
@pauljeter @collab-ui/collab-jedi
> feat(slider): Fixing the alignment issue of slider label

- src/lib/EditableTextfield/index.spec.js
> feat(EditableTextfield): Added test cases for key handling

- package-lock.json
- src/lib/List/index.js
- src/lib/Modal/index.spec.js
- src/lib/SpaceListItem/__snapshots__/index.spec.js.snap
- src/lib/SpaceListItem/index.js
- src/lib/SpaceListItem/index.spec.js
- src/lib/SpaceListMeeting/index.js
- src/lib/SpaceListMeeting/index.spec.js
- fix(SpaceList): change Header/SubHeader to Node propType
- fix(Modal): adjust deprecated test method
> fix(SpaceMeeting): allow avatar to be passed in

- package-lock.json
- package.json
- src/docs/containers/Playground/insertExampleHere.js
- src/lib/AlertCall/DeviceListCall/__snapshots__/index.spec.js.snap
- src/lib/List/index.js
- src/lib/ListItemHeader/__snapshots__/index.spec.js.snap
- src/lib/ListItemHeader/index.js
- src/lib/ListItemHeader/index.spec.js
- src/lib/SpaceListItem/__snapshots__/index.spec.js.snap
- src/lib/SpaceListItem/index.js
- src/lib/SpaceListItem/index.spec.js
> feat(SpaceListItem): added filter,search, and tests

- src/lib/Alert/__snapshots__/index.spec.js.snap
- src/lib/Alert/index.js
- src/lib/AlertCall/__snapshots__/index.spec.js.snap
- src/lib/AlertCall/index.js
- src/lib/AlertCallContainer/__snapshots__/index.spec.js.snap
- src/lib/AlertCallContainer/index.js
- src/lib/AlertCallContainer/index.spec.js
- src/lib/AlertContainer/__snapshots__/index.spec.js.snap
- src/lib/AlertContainer/index.js
- src/lib/AlertContainer/index.spec.js
- src/lib/AlertMeeting/__snapshots__/index.spec.js.snap
- src/lib/AlertMeeting/index.js
- src/lib/AlertMeetingContainer/__snapshots__/index.spec.js.snap
- src/lib/AlertMeetingContainer/index.js
- src/lib/AlertMeetingContainer/index.spec.js
- src/lib/index.js
> AlertContainer, AlertMeetingContainer, and AlertCallContainer Implementations

- src/lib/AlertCall/DeviceListCall/index.spec.js
- src/lib/AlertMeeting/__snapshots__/index.spec.js.snap
- src/lib/AlertMeeting/index.js
- src/lib/AlertMeeting/index.spec.js
> feat(AlertMeeting): Add onClick handler and make snooze button optional.

- src/lib/Icon/__snapshots__/index.spec.js.snap
- src/lib/Icon/index.js
- src/lib/Icon/index.spec.js
> fix(Icon): change error to warning

- src/lib/Avatar/index.js
- src/lib/Avatar/index.spec.js
> feat(Avatar): add self type

- src/lib/Avatar/index.js
- src/lib/Avatar/index.spec.js
> feat(Avatar): added logic for 40px Self Avatar

- src/lib/ActivityButton/__snapshots__/index.spec.js.snap
- src/lib/AlertCall/DeviceListCall/__snapshots__/index.spec.js.snap
- src/lib/AlertCall/__snapshots__/index.spec.js.snap
- src/lib/AlertMeeting/__snapshots__/index.spec.js.snap
- src/lib/Button/__snapshots__/index.spec.js.snap
- src/lib/Button/index.js
- src/lib/Button/index.spec.js
- src/lib/CallControl/__snapshots__/index.spec.js.snap
- src/lib/CollapseButton/__snapshots__/index.spec.js.snap
- src/lib/Icon/__snapshots__/index.spec.js.snap
- src/lib/Icon/index.js
- src/lib/Icon/index.spec.js
- src/lib/Lightbox/__snapshots__/index.spec.js.snap
- src/lib/SearchInput/__snapshots__/index.spec.js.snap
- src/lib/Select/__snapshots__/index.spec.js.snap
- src/lib/TopbarMobile/__snapshots__/index.spec.js.snap
> feat(Icon): added Icon type

- src/lib/Avatar/index.js
- src/lib/CompositeAvatar/index.js
- src/lib/CompositeAvatar/index.spec.js
- src/lib/SpaceListMeeting/index.spec.js
> feat(CompositeAvatar): added size 84

- src/lib/List/index.js
- src/lib/ListItem/index.js
- src/lib/ListItemMeeting/__snapshots__/index.spec.js.snap
- src/lib/ListItemMeeting/index.js
- src/lib/ListItemMeeting/index.spec.js
- src/lib/index.js
> feat(ListItemMeeting): component created

- src/lib/SpaceListMeeting/__snapshots__/index.spec.js.snap
- src/lib/SpaceListMeeting/index.js
- src/lib/SpaceListMeeting/index.spec.js
>  fix(SpaceListMeeting): added isBold prop for Header

- src/lib/Coachmark/__snapshots__/index.spec.js.snap
- src/lib/Coachmark/index.js
- src/lib/Coachmark/index.spec.js
- src/lib/EventOverlay/index.js
- src/lib/Popover/index.js
> fix(Coachmark): made allowClickAway prop changeable

- src/lib/DatePicker/DatePickerCalendar/index.js
- src/lib/DatePicker/DatePickerCalendar/index.spec.js
- src/lib/DatePicker/DatePickerDay/__snapshots__/index.spec.js.snap
- src/lib/DatePicker/DatePickerDay/index.js
- src/lib/DatePicker/DatePickerDay/index.spec.js
- src/lib/DatePicker/DatePickerMonth/__snapshots__/index.spec.js.snap
- src/lib/DatePicker/DatePickerMonth/index.js
- src/lib/DatePicker/DatePickerMonth/index.spec.js
- src/lib/DatePicker/DatePickerWeek/__snapshots__/index.spec.js.snap
- src/lib/DatePicker/DatePickerWeek/index.js
- src/lib/DatePicker/DatePickerWeek/index.spec.js
- src/lib/DatePicker/__snapshots__/index.spec.js.snap
- src/lib/DatePicker/date_utils.js
- src/lib/DatePicker/index.js
- src/lib/DatePicker/index.spec.js
- src/lib/Input/index.js
- src/lib/Input/index.spec.js
- src/lib/index.js
> feat(DatePicker): DatePicker component implementation

- src/lib/Avatar/index.js
> fix(avatar): state is not updated on avatarUrl change

- src/lib/EditableTextfield/__snapshots__/index.spec.js.snap
- src/lib/EditableTextfield/index.js
- src/lib/EditableTextfield/index.spec.js
> feat(EditableTextfield): allow classes and props to be passed in

- src/lib/Menu/__snapshots__/index.spec.js.snap
- src/lib/Menu/index.js
- src/lib/Menu/index.spec.js
- src/lib/MenuItem/__snapshots__/index.spec.js.snap
- src/lib/MenuItem/index.spec.js
- src/lib/MenuOverlay/__snapshots__/index.spec.js.snap
- src/lib/MenuOverlay/index.js
- src/lib/SubMenu/__snapshots__/index.spec.js.snap
- src/lib/SubMenu/index.js
- src/lib/SubMenu/index.spec.js
- src/lib/index.js
> Menu item rework

- src/lib/SpaceListItem/index.js
- src/lib/SpaceListItem/index.spec.js
> fix(SpaceListItem): add regex escape for special characters

- src/lib/CallControl/__snapshots__/index.spec.js.snap
- src/lib/CallControl/index.js
- src/lib/CallControl/index.spec.js
> Call control icon

- src/docs/containers/Playground/insertExampleHere.js
- src/lib/List/index.js
- src/lib/ListItem/index.js
- src/lib/Select/index.js
- src/lib/Select/index.spec.js
- src/lib/SelectOption/__snapshots__/index.spec.js.snap
- src/lib/SelectOption/index.js
> fix(Select): add value prop, fix onSelect function

- src/lib/Lightbox/__snapshots__/index.spec.js.snap
- src/lib/Loading/index.js
- src/lib/Spinner/__snapshots__/index.spec.js.snap
- src/lib/Spinner/index.js
- src/lib/Spinner/index.spec.js
-Added checkmark to show inside spinner if showCheck is true and percentage is 100.
-added test to check for class 'cui-spinner-progress__inset-circle--check'
> Spinner checkmark added 

- src/lib/Avatar/index.js
> docs(Avatar): show all sizes with DND/OOO icons

- src/lib/EditableTextfield/__snapshots__/index.spec.js.snap
- src/lib/EditableTextfield/index.js
- src/lib/EditableTextfield/index.spec.js
- src/lib/Input/index.js
- yarn.lock
Resolves: https://github.com/collab-ui/collab-ui-react/issues/129
>  fix(EditableTextfield): allow empty value for EditableTextfield

- src/lib/AlertCall/__snapshots__/index.spec.js.snap
- src/lib/AlertMeeting/__snapshots__/index.spec.js.snap
- src/lib/Avatar/__snapshots__/index.spec.js.snap
- src/lib/Avatar/index.js
- src/lib/Avatar/index.spec.js
- src/lib/CompositeAvatar/__snapshots__/index.spec.js.snap
- src/lib/SpaceListItem/__snapshots__/index.spec.js.snap
- src/lib/SpaceListMeeting/__snapshots__/index.spec.js.snap
> feat(Avatar): add notification badge

- src/lib/Accordion/__snapshots__/index.spec.js.snap
- src/lib/ListItemMeeting/__snapshots__/index.spec.js.snap
- src/lib/ListItemMeeting/index.js
- src/lib/ListItemMeeting/index.spec.js
- src/lib/ListItemSection/index.js
- src/lib/ListSeparator/__snapshots__/index.spec.js.snap
- src/lib/ListSeparator/index.spec.js
- src/lib/TopbarMobile/__snapshots__/index.spec.js.snap
- yarn.lock
1. Add prop for statusColor to change color of left status indicator.
2. Add prop includeDate boolean to adjust style of date/time info as seen in invision.   
-  Move date on top; start time - end time under
3. Add date prop to pass in date ex: (date = 'January 28, 2015')
> List item Meeting Update

- src/lib/ButtonGroup/index.js
- src/lib/ButtonGroup/index.spec.js
- src/lib/Icon/index.js
> Button group - add pill/color style

- src/lib/AlertCall/__snapshots__/index.spec.js.snap
- src/lib/AlertMeeting/__snapshots__/index.spec.js.snap
- src/lib/Avatar/__snapshots__/index.spec.js.snap
- src/lib/Avatar/index.js
- src/lib/Avatar/index.spec.js
- src/lib/CompositeAvatar/__snapshots__/index.spec.js.snap
- src/lib/SpaceListItem/__snapshots__/index.spec.js.snap
- src/lib/SpaceListItem/index.js
- src/lib/SpaceListItem/index.spec.js
- src/lib/SpaceListMeeting/__snapshots__/index.spec.js.snap
This pull request will add an isDecrypting prop to apply a blur style that will be added in collab-ui-core to allow the widgets to blur space information while the content is still decrypting.
The collab-ui-core pull request can be found [here](https://github.com/collab-ui/collab-ui-core/pull/116)
> feat(SpaceListItem): add isDecrypting prop

- src/lib/ContentItem/ChatContent/index.js
- src/lib/ContentItem/FileContent/index.js
- src/lib/ContentItem/IconContent/index.js
- src/lib/ContentItem/__snapshots__/index.spec.js.snap
- src/lib/ContentItem/index.js
- src/lib/ContentItem/index.spec.js
- src/lib/index.js
- src/lib/utils/snakeCase/index.js
File View, Chat View, Icon, Different Sizes, Failed to load, loading content
> Content Item Component 

- src/lib/Avatar/index.js
- src/lib/Avatar/index.spec.js
resolves https://github.com/collab-ui/collab-ui-core/issues/90
When a user hovers or presses on a clickable avatar, the avatar becomes a little darker.
> fix(avatar): add hover/pressed states when clickable

- src/lib/CallControl/index.js
- src/lib/DatePicker/index.js
- src/lib/ListItem/index.js
- src/lib/SpaceListItem/index.js
Displays a few of the new contrasting values from collab-core. This PR should only affect the rendered examples, no actual code changes.
Related: https://github.com/collab-ui/collab-ui-core/pull/127
> feat(contrast): displaying contrast versions in the docs

- README.md
Links to old cisco site
Links to current github
> docs(README): update collab-ui github links

- src/lib/ContentItem/FileContent/index.js
- src/lib/ContentItem/index.js
updated sixteenNine file example, image will be background-size contain instead of cover on wide
fix for gifIcon placement on oneOne and fourThree
> fix(ContentItem): update sixteenNine file example

- src/lib/Avatar/index.js
Avatar image will render on SSR applications on reload. 
> fix(Avatar): fix to render avatar image on SSR applications

- src/lib/ContentItem/FileContent/index.js
Fix for tall images in fileContentItem. 
> fix(contentItem): fix for tall images with FileContentItem

- src/lib/SideNav/index.js
> fix(SideNav): fix lint error in SideNav

- src/lib/SideNav/index.js
Arrows were reversed in SideNav dropdown.
Arrows are now correct.
> fix(SideNav): reverse SideNav Arrows

- src/lib/CallControl/__snapshots__/index.spec.js.snap
- src/lib/CallControl/index.js
- src/lib/CallControl/index.spec.js
> feat(CallControl): add iconColor prop to CallControl
